### ISSUE TITLE
ActiveRecord::StatementInvalid: PG::DuplicateObject: ERROR:  trigger "layer_integrity_checks" for relation "layer" already exists

### ISSUE THREAD

**Issue by cj** [teoljungberg/fx#67]
rails 6.1.3
fx 0.6.2

When using github actions, I am getting this error:

```
ActiveRecord::StatementInvalid: PG::DuplicateObject: ERROR:  trigger "layer_integrity_checks" for relation "layer" already exists
/home/runner/work/***/***/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:47:in `exec'
/home/runner/work/***/***/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:47:in `block (2 levels) in execute'
/home/runner/work/***/***/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/home/runner/work/***/***/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/home/runner/work/***/***/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/home/runner/work/***/***/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:46:in `block in execute'
/home/runner/work/***/***/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3/lib/active_record/connection_adapters/abstract_adapter.rb:696:in `block (2 levels) in log'
/home/runner/work/***/***/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/home/runner/work/***/***/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/home/runner/work/***/***/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/home/runner/work/***/***/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/home/runner/work/***/***/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/home/runner/work/***/***/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3/lib/active_record/connection_adapters/abstract_adapter.rb:695:in `block in log'
/home/runner/work/***/***/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/home/runner/work/***/***/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3/lib/active_record/connection_adapters/abstract_adapter.rb:687:in `log'
/home/runner/work/***/***/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:45:in `execute'
/home/runner/work/***/***/vendor/bundle/ruby/3.0.0/gems/fx-0.6.2/lib/fx/adapters/postgres.rb:152:in `execute'
/home/runner/work/***/***/vendor/bundle/ruby/3.0.0/gems/fx-0.6.2/lib/fx/adapters/postgres.rb:84:in `create_trigger'
/home/runner/work/***/***/vendor/bundle/ruby/3.0.0/gems/fx-0.6.2/lib/fx/statements/trigger.rb:49:in `create_trigger'
/home/runner/work/***/***/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3/lib/active_record/migration.rb:929:in `block in method_missing'
/home/runner/work/***/***/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3/lib/active_record/migration.rb:897:in `block in say_with_time'
/home/runner/work/***/***/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3/lib/active_record/migration.rb:897:in `say_with_time'
/home/runner/work/***/***/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3/lib/active_record/migration.rb:918:in `method_missing'
/home/runner/work/***/***/db/schema.rb:1136:in `block in <main>'
/home/runner/work/***/***/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3/lib/active_record/schema.rb:50:in `instance_eval'
/home/runner/work/***/***/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3/lib/active_record/schema.rb:50:in `define'
/home/runner/work/***/***/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3/lib/active_record/schema.rb:46:in `define'
/home/runner/work/***/***/db/schema.rb:14:in `<main>'
```

Here is a copy of my schema https://gist.github.com/cj/bb62776913387c17ca1dc9c1c3ae394c

Locally it is working fine, the problem seems to just be when running it on github actions.  Here is a copy of my github action https://gist.github.com/cj/ba6aca746cbc84afba1a1b510979889d

If this is unrelated to FX please let me know and I can close the issue.

Cheers!

**Comment by teoljungberg** [comment]
In your function and trigger definition, consider using create or replace. I guess you're not?
