### ISSUE TITLE
Procedure is being converted into function in trigger definition

### ISSUE THREAD

**Issue by harry-graham** [teoljungberg/fx#85]
I'm not sure if I'm doing something wrong, but when I have a trigger such as the following, under db/triggers:

```sql
CREATE TRIGGER trigger_name
    BEFORE INSERT OR UPDATE ON table_name
    FOR EACH ROW EXECUTE PROCEDURE
    function_name();
```

With a migration as follows:
```ruby
class CreateTriggerTriggerName < ActiveRecord::Migration[5.2]
  def change
    create_trigger :trigger_name, on: :table_name
  end
end
```

Running the migration adds the trigger to the schema, but converts the `PROCEDURE` to a `FUNCTION`, as follows:
```ruby
  create_trigger :trigger_name, sql_definition: <<-SQL
      CREATE TRIGGER trigger_name BEFORE INSERT OR UPDATE ON public.table_name FOR EACH ROW EXECUTE FUNCTION function_name()
  SQL
```

Is this expected behaviour? Is there any way to override/prevent it? Our app needs a PROCEDURE and not a FUNCTION to be run by the trigger.

**Comment by teoljungberg** [comment]
That speaks to be about a difference in postgres versions - one syntax (I forgot which version) uses `PROCEDURE` - the other uses `FUNCTION`.

When I wrote this gem in ~2016 I worked on postgres 10 (ish).

It might be that we've run out of sync with what modern postgres version are, and how they behave and expect.

**Comment by harry-graham** [comment]
Is there a reason for not just using the exact SQL definition from the trigger file, when inserting it into the schema?

**Comment by harry-graham** [comment]
Ran tests locally with PostgreSQL 14.0, this is possibly the only compatibility issue.

```
Failures:

  1) Fx::SchemaDumper::Trigger dumps a create_trigger for a trigger in the database
     Failure/Error: expect(output).to include "EXECUTE PROCEDURE uppercase_users_name()"

       expected "# This file is auto-generated ... BEFORE INSERT ON public.users FOR EACH ROW EXECUTE FUNCTION uppercase_users_name()\n  SQL\nend\n" to include "EXECUTE PROCEDURE uppercase_users_name()"

     # ./spec/fx/schema_dumper/trigger_spec.rb:38:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:13:in `block (2 levels) in <top (required)>'

  2) Fx::Adapters::Postgres::Triggers.all returns `Trigger` objects
     Failure/Error: expect(first.definition).to include("EXECUTE PROCEDURE uppercase_users_name()")
       expected "CREATE TRIGGER uppercase_users_name BEFORE INSERT ON public.users FOR EACH ROW EXECUTE FUNCTION uppercase_users_name()" to include "EXECUTE PROCEDURE uppercase_users_name()"
     # ./spec/fx/adapters/postgres/triggers_spec.rb:40:in `block (3 levels) in <module:Adapters>'
     # ./spec/spec_helper.rb:13:in `block (2 levels) in <top (required)>'

Finished in 0.36324 seconds (files took 1.09 seconds to load)
87 examples, 2 failures


Failed examples:

rspec ./spec/fx/schema_dumper/trigger_spec.rb:4 # Fx::SchemaDumper::Trigger dumps a create_trigger for a trigger in the database
rspec ./spec/fx/adapters/postgres/triggers_spec.rb:7 # Fx::Adapters::Postgres::Triggers.all returns `Trigger` objects
```

**Comment by harry-graham** [comment]
The gem still works with PostgreSQL 14, it failed for my use case due to using different db versions in different environments.

Sorry for the noise, and thanks for the advice! 🙏🏼
